// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH3e0XthvtdX1qFDkqaIcaGvZoJaB1QGk',
    appId: '1:204125955644:web:660eba086e8ca8f2fac539',
    messagingSenderId: '204125955644',
    projectId: 'real-estate-app-27e94',
    authDomain: 'real-estate-app-27e94.firebaseapp.com',
    storageBucket: 'real-estate-app-27e94.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtQI9UrDxxfjF_PMX1ij8qu5qUxAOzLPQ',
    appId: '1:204125955644:ios:fcfde31f8ec78ed4fac539',
    messagingSenderId: '204125955644',
    projectId: 'real-estate-app-27e94',
    storageBucket: 'real-estate-app-27e94.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtQI9UrDxxfjF_PMX1ij8qu5qUxAOzLPQ',
    appId: '1:204125955644:ios:fcfde31f8ec78ed4fac539',
    messagingSenderId: '204125955644',
    projectId: 'real-estate-app-27e94',
    storageBucket: 'real-estate-app-27e94.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB66E7ELh_cn3ZwTHIaRMiDnQW-pAO_K2s',
    appId: '1:204125955644:android:e24c94451485abfbfac539',
    messagingSenderId: '204125955644',
    projectId: 'real-estate-app-27e94',
    storageBucket: 'real-estate-app-27e94.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH3e0XthvtdX1qFDkqaIcaGvZoJaB1QGk',
    appId: '1:204125955644:web:108c58383929d204fac539',
    messagingSenderId: '204125955644',
    projectId: 'real-estate-app-27e94',
    authDomain: 'real-estate-app-27e94.firebaseapp.com',
    storageBucket: 'real-estate-app-27e94.firebasestorage.app',
  );

}